Add missing use statement so errors aren't issued
A missed use statement is causing errors in use. Adding the correct
namespace to be used will resolve the error below.

Error: Class "Tractorcow\CampaignMonitor\LogLevel" not found